### ISSUE TITLE
[FEATURE REQUEST] DC version

### ISSUE THREAD

**Issue by WMP** [nliaudat/esp32_8ch_motor_shield#34]
Do you plan to continue developing the DC version? Unfortunately, the HLK-5M03 power supply has low efficiency.

**Comment by nliaudat** [comment]
Hello, 

I don't think so because the idea was for me to find contributors. 

This not being the case and not having any more time, I think that the DC version will disappear. Anyway, the DC version needed a separate AC power supply. 

Personally, I think the HLK-5M03 module has a good price/performance ratio. 
You can always skip it and power the board directly with 3.3 or 5V with your own power supply module. 

Regards
